### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 35.0
        sensor_timeout: 0.1
        two_d_mode: true
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true
        debug: false
        permit_corrected_publication: false
        publish_acceleration: false
        publish_tf: true


        # map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        # ODOM0: RAW ENCODERS
        odom0: raw_odom
        odom0_config: [false, false, false,
                       false, false, false,
                       true,  true,  false,
                       false, false, false,
                       false, false, false]
        odom0_queue_size: 3
        odom0_nodelay: true
        odom0_differential: false
        odom0_relative: true
        odom0_pose_rejection_threshold: 1.0
        odom0_twist_rejection_threshold: 1.0

        # IMU0: VECTORNAV IMU
        imu0: vectornav/imu
        imu0_config:  [false, false, false,
                       false, false, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]
        imu0_queue_size: 3
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true
        imu0_twist_rejection_threshold: 0.8
        imu0_linear_acceleration_rejection_threshold: 0.8 
        imu0_remove_gravitational_acceleration: true

        # initial_state: [0.0,  0.0,  0.0,
        #                 0.0,  0.0,  0.0,
        #                 0.0,  0.0,  0.0,
        #                 0.0,  0.0,  0.0,
        #                 0.0,  0.0,  0.0]


        use_control: true
        stamped_control: false
        control_timeout: 0.2
        control_config: [true, true, false, false, false, true]
        acceleration_limits: [0.3, 0.0, 0.0, 0.0, 0.0, 0.15]
        deceleration_limits: [0.3, 0.0, 0.0, 0.0, 0.0, 0.15]
        acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
        deceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]

        smooth_lagged_data: true
        history_length: 0.5

        process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.005, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.03,  0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.03,  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
        
        dynamic_process_noise_covariance: true
                                    #  x     y     z      r     p     y      vx    vy    vz    vr    vp    vy    ax    ay    az
        initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-3, 1e-4, 1e-4, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9]
        # initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 145.0, 1e-11, 1e-13, 1e-9, 1e-9, 1e-9, 145.0, 1e-9, 1e-9, 1e-9]
